import type { BrandState } from '@/types/brand'

export function generateTailwindExport(state: BrandState): string {
  const { lightPalette, headingFont, bodyFont } = state

  const gradientExtension: string = state.gradientCSS !== null
    ? `
      backgroundImage: {
        'gradient-primary': "${state.gradientCSS}",
      },`
    : ''

  return `// tailwind.config.ts - Generated by brandstylegenerator.com
// Brand: ${state.name}

import type { Config } from "tailwindcss"

export default {
  theme: {
    extend: {
      colors: {
        primary: "${lightPalette.primary}",
        secondary: "${lightPalette.secondary}",
        tertiary: "${lightPalette.tertiary}",
        accent: "${lightPalette.accent}",
        "on-primary": "${lightPalette.onPrimary}",
        "on-secondary": "${lightPalette.onSecondary}",
        "on-tertiary": "${lightPalette.onTertiary}",
        "on-accent": "${lightPalette.onAccent}",
        background: "${lightPalette.bg}",
        surface: {
          DEFAULT: "${lightPalette.surface}",
          raised: "${lightPalette.surfaceRaised}",
        },
        border: "${lightPalette.border}",
        text: {
          DEFAULT: "${lightPalette.text}",
          muted: "${lightPalette.textMuted}",
        },
        success: "${lightPalette.success}",
        warning: "${lightPalette.warning}",
        error: "${lightPalette.error}",
      },${gradientExtension}
      fontFamily: {
        heading: ["${headingFont}", "system-ui", "sans-serif"],
        body: ["${bodyFont}", "system-ui", "sans-serif"],
      },
      borderRadius: {
        sm: "6px",
        md: "8px",
        lg: "12px",
        xl: "16px",
      },
    },
  },
} satisfies Config`
}
