import type { BrandState } from '@/types/brand'

export function generateCSSExport(state: BrandState): string {
  const { lightPalette, darkPalette, headingFont, bodyFont } = state

  const gradientLine: string = state.gradientCSS !== null
    ? `\n  /* Gradient Primary */\n  --gradient-primary: ${state.gradientCSS};`
    : ''

  return `/* Generated by brandstylegenerator.com */
/* Brand: ${state.name} */

:root {
  /* Colors - Light Mode */
  --color-primary: ${lightPalette.primary};${gradientLine}
  --color-secondary: ${lightPalette.secondary};
  --color-tertiary: ${lightPalette.tertiary};
  --color-accent: ${lightPalette.accent};
  --color-bg: ${lightPalette.bg};
  --color-surface: ${lightPalette.surface};
  --color-surface-raised: ${lightPalette.surfaceRaised};
  --color-border: ${lightPalette.border};
  --color-text: ${lightPalette.text};
  --color-text-muted: ${lightPalette.textMuted};
  --color-success: ${lightPalette.success};
  --color-warning: ${lightPalette.warning};
  --color-error: ${lightPalette.error};

  /* Typography */
  --font-heading: '${headingFont}', system-ui, sans-serif;
  --font-body: '${bodyFont}', system-ui, sans-serif;
  --font-heading-weight: ${state.headingWeight};
  --font-body-weight: ${state.bodyWeight};

  /* Font Sizes */
  --text-xs: 0.75rem;
  --text-sm: 0.875rem;
  --text-base: 1rem;
  --text-lg: 1.125rem;
  --text-xl: 1.25rem;
  --text-2xl: 1.5rem;
  --text-3xl: 1.875rem;
  --text-4xl: 2.25rem;
  --text-5xl: 3rem;

  /* Border Radius */
  --radius-sm: 6px;
  --radius-md: 8px;
  --radius-lg: 12px;
  --radius-xl: 16px;
}

/* Dark Mode Override */
[data-theme="dark"],
.dark {
  --color-primary: ${darkPalette.primary};
  --color-secondary: ${darkPalette.secondary};
  --color-tertiary: ${darkPalette.tertiary};
  --color-accent: ${darkPalette.accent};
  --color-bg: ${darkPalette.bg};
  --color-surface: ${darkPalette.surface};
  --color-surface-raised: ${darkPalette.surfaceRaised};
  --color-border: ${darkPalette.border};
  --color-text: ${darkPalette.text};
  --color-text-muted: ${darkPalette.textMuted};
  --color-success: ${darkPalette.success};
  --color-warning: ${darkPalette.warning};
  --color-error: ${darkPalette.error};
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
    --color-primary: ${darkPalette.primary};
    --color-secondary: ${darkPalette.secondary};
    --color-tertiary: ${darkPalette.tertiary};
    --color-accent: ${darkPalette.accent};
    --color-bg: ${darkPalette.bg};
    --color-surface: ${darkPalette.surface};
    --color-surface-raised: ${darkPalette.surfaceRaised};
    --color-border: ${darkPalette.border};
    --color-text: ${darkPalette.text};
    --color-text-muted: ${darkPalette.textMuted};
    --color-success: ${darkPalette.success};
    --color-warning: ${darkPalette.warning};
    --color-error: ${darkPalette.error};
  }
}`
}
